### PR TITLE
Added hosts and swap

### PR DESCRIPTION
**Pull request by masylum**
With tests updated and passing.

### CODE REVIEW

**Comment by karmi** [comment]
Hi Pau, awesome, thanks, it was on my TODO list as well.

I've split & cleaned up your commits a bit, see the compare: https://github.com/karmi/monittr/compare/v0.0.4...v0.0.5

It's included in current 0.0.5 release,

regards,

Karel

**Comment by karmi** [comment]
Ugh, I've reused your committer info from the repo, and apparently you've got another email for Github account, so the avatars are missing, sorry about that.

**Comment by masylum** [comment]
Thanks to you! 
We started using this gem two days ago to monitor our machines and it rocks!
If you add http authentication on the example, anyone (even non rubyists) can have it production ready in 5 minutes.

**Comment by karmi** [comment]
Yeah, I should make the example application more standalone and easily deployable by itself, so people without existing admin apps can run just that. Regards, K.

**Pull request closed without merging**
